### ISSUE TITLE
Pullapprove is marking PRs approved before they have sufficient reviews

### ISSUE THREAD

**Issue by bzbarsky-apple** [dropseed/pullapprove#71]
We have not changed our `.pullapprove.yml` https://github.com/project-chip/connectedhomeip/blob/be248543eb11d956ba897285b2f558751b25e0a5/.pullapprove.yml at  in a few months, and it has this bit:
```
    required-reviewers:
        requirements:
            - len(groups.approved.include('shared-reviewers-*')) >= 2
```

but PRs are being marked as approved with only one review.  For example https://github.com/project-chip/connectedhomeip/pull/25624 only has review from 1 person and the job listing says:

> pullapprove — 1 group approved 

but the pullapprove job has a green check, etc.

It looks like some people are being counted as being in shared-reviewers-signify even though it's defined like so:
```
    shared-reviewers-signify:
        type: optional
        conditions:
            - files.include('*')
        reviewers:
            teams: [reviewers-signify]
        reviews:
            request: 10
```
and the `reviewers-signify` team has 0 members.  And then a review from one of them counts as "2 groups" even though pullapprove is still saying "1 group approved"...
